// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.0.5

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type ManageHTTPServer interface {
	Ping(context.Context, *PingReq) (*PingResp, error)
}

func RegisterManageHTTPServer(s *http.Server, srv ManageHTTPServer) {
	r := s.Route("/")
	r.GET("/interface-manage/manage/v1/ping", _Manage_Ping0_HTTP_Handler(srv))
}

func _Manage_Ping0_HTTP_Handler(srv ManageHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PingReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/manage.v1.Manage/Ping")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Ping(ctx, req.(*PingReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PingResp)
		return ctx.Result(200, reply)
	}
}

type ManageHTTPClient interface {
	Ping(ctx context.Context, req *PingReq, opts ...http.CallOption) (rsp *PingResp, err error)
}

type ManageHTTPClientImpl struct {
	cc *http.Client
}

func NewManageHTTPClient(client *http.Client) ManageHTTPClient {
	return &ManageHTTPClientImpl{client}
}

func (c *ManageHTTPClientImpl) Ping(ctx context.Context, in *PingReq, opts ...http.CallOption) (*PingResp, error) {
	var out PingResp
	pattern := "/interface-manage/manage/v1/ping"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/manage.v1.Manage/Ping"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
