// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/ffy/kratos-layout/internal/biz"
	"github.com/ffy/kratos-layout/internal/conf"
	"github.com/ffy/kratos-layout/internal/data"
	"github.com/ffy/kratos-layout/internal/server"
	"github.com/ffy/kratos-layout/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	manageRepo := data.NewManageRepo(dataData, logger)
	manageUseCase := biz.NewManageUseCase(manageRepo, logger)
	manageService := service.NewManageService(manageUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, manageService, logger)
	grpcServer := server.NewGRPCServer(confServer, manageService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
